In [1]:
#numpy
#numpy stands for "numerical python",is a popular python library for numerical and scientific computing.
#it provides support for working with large multidimensional arrys and matrices  of data,
#along with a collection of mathematical functional to operate on these arrays.

#features:
#1.multidimensional
#2.efficient and fast
#3.Broadcasting
#4.elemnet wise operations.
#5.mathematical functions.
#6.random number generation


In [2]:
import numpy as np

list=[112,1,5]
arr=np.array(list)
print(arr)

[112   1   5]


In [3]:
a=np.array(42)
b=np.array([2,4,5])
c=np.array([[2,3,4],[5,6,7]])
d=([[[2,4,6],[2,4,5],[2,4,4]]])
print(a)
print(b)
print(c)
print(d)

42
[2 4 5]
[[2 3 4]
 [5 6 7]]
[[[2, 4, 6], [2, 4, 5], [2, 4, 4]]]


In [7]:
a=np.array(42)
b=np.array([2,4,5])
c=np.array([[2,3,4],[5,6,7]])
d=np.array([[[2,4,6],[2,4,5],[2,4,4],[2,3,3]]])
print(a)
print(b)
print(c)
print(d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

42
[2 4 5]
[[2 3 4]
 [5 6 7]]
[[[2 4 6]
  [2 4 5]
  [2 4 4]
  [2 3 3]]]
0
1
2
3


In [8]:
#shape 
#1d array-vector
#2d array-matrix
#3d array-tensor

In [12]:
arr=np.array([[2,3,4],[5,6,7]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[2 3 4]
 [5 6 7]]
2
(2, 3)


In [13]:
#slicing


In [14]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [16]:
arr=np.array([1,2,3,4,5,6,7])
sarr=arr[1:5]
print(sarr)
sarr[2]=100
print(arr)
print(sarr)

[2 3 4 5]
[  1   2   3 100   5   6   7]
[  2   3 100   5]


In [20]:
#difference between copy and view

#the copy owns the data any changes made to the copy will not affect original array ,
#and any changes made to the original array will not affect the copy 

# the view does'nt own the data and any changes made to the view will affect the original array and
#any changes made to the original array will effect the view


In [21]:
#copy

arr=np.array([1,2,3,4,5,6,7])
arr2=arr.copy()
arr[0]=42
print(arr)
print(arr2)


[42  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


In [26]:
#view

arr=np.array([1,2,3,4,5,6,7])
arr2=arr.view()
arr[0]=42
print(arr)
print(arr2)


[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


In [23]:
 #zeros

a=np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
#ones
a=np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
a=np.ones((5,2))*10
a

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [29]:
a=np.ones((6,),dtype=int)
print(a)

[1 1 1 1 1 1]


In [32]:
#create array with hetrogenous datatype
a=np.ones((6,),dtype=[('x','int'),('y','float')])
print(a)

[(1, 1.) (1, 1.) (1, 1.) (1, 1.) (1, 1.) (1, 1.)]


In [34]:
#eye function is used to give number diagonally

arr4=np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr4=np.eye(3)
print(arr4)
arr4=np.eye(3,4)
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [40]:
#diag 
arr5=np.diag((3,4,3,5))
arr5
print(arr5.ndim)
print(arr5.shape)

2
(4, 4)
