In [5]:
import numpy as np 
c=np.array([[1,2,3],[4,5,6],[4,5,6]])
print(np.diag(c))

[1 5 6]


In [7]:
import numpy as np 
c=np.array([[1,2,3],[4,5,6],[4,5,6]])
print(np.diag(c))


print(np.diag((3,9,5)))

[1 5 6]
[[3 0 0]
 [0 9 0]
 [0 0 5]]


In [ ]:
# randint() is an ibuilt function of the random module in python 3 . the random module gives access to various useful functuon one of the them being able to generate random numbers , which is randint() 

In [13]:
rand=np.random.randint(1,10,6)
print(rand)

[4 8 6 1 7 4]


In [ ]:
# this function generates an array of specified shape and fills it with random samples from a uniform distriubution over the interval[0,1)

In [21]:
rand=np.random.rand(4)
print(rand)

[0.59094488 0.29439114 0.05520265 0.21535927]


In [23]:
rand=np.random.rand(2,3)
print(rand)

[[0.44854091 0.21716783 0.85181952]
 [0.30219008 0.92127796 0.34948406]]


In [49]:
arr=np.random.randint(1,10,6)
print(arr)
arr=arr.reshape(2,3)
print(arr)

[7 7 4 8 1 1]
[[7 7 4]
 [8 1 1]]


In [31]:
# the reshape function in numpy allow you to change the shape (dimension) of an array without changing its data . this can be usefull when u want to rearrange the way daya is organized in an array , such as converting a 
# 1-dimension array into a 2 dinmensionl matrix or vice cversa or changing the size of a multi-dimensional array maintaining the total number of elements 

In [35]:
arr=np.random.randint(0,100,12)
print(arr)
arr=arr.reshape(4,3)
print(arr)
print("Array value is ",arr[0][1])
print("Array value is ", arr[1][0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr)
arr=arr.reshape(2,-1)
print(arr)

[45 92 83 21 84 33 26 86 85 30 51 79]
[[45 92 83]
 [21 84 33]
 [26 86 85]
 [30 51 79]]
Array value is  92
Array value is  21
(4, 3)
[[45 92 83 21]
 [84 33 26 86]
 [85 30 51 79]]
[[45 92 83 21 84 33]
 [26 86 85 30 51 79]]


In [55]:
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [69]:
np.random.seed(145)
arr=np.random.randint(0,500,30).reshape(6,5)
print(arr)

[[ 37 106 379 470 471]
 [146  90 453   8 309]
 [289 242 160 168 154]
 [468 101  29  10 111]
 [109   8 473  33 390]
 [279 390 365 168 322]]


In [71]:
print(arr[2:,2:])
print(arr[3:5,2:4])

[[160 168 154]
 [ 29  10 111]
 [473  33 390]
 [365 168 322]]
[[ 29  10]
 [473  33]]


In [79]:
ar=np.array([1,20,5,9,3,4,5,6,2,25,2,2265,3,33])
slicing=ar[4:9]
print("new slicing",slicing)
print("new array",ar)
print(type(slicing))
print(type(ar))
slicing[:]=0
print("old slicing",slicing)
print("old array",arr)

new slicing [3 4 5 6 2]
new array [   1   20    5    9    3    4    5    6    2   25    2 2265    3   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old slicing [0 0 0 0 0]
old array [[ 37 106 379 470 471]
 [146  90 453   8 309]
 [289 242 160 168 154]
 [468 101  29  10 111]
 [109   8 473  33 390]
 [279 390 365 168 322]]


In [83]:
ar=np.arange(1,15)
print(ar)
print(ar[ar%2==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [85]:
ar=np.arange(1,15)
print(ar)
print(ar[ar%2!=0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]


In [91]:
ar=np.arange(1,15)
print(ar)
print(ar[ar%2==0])
print(ar[ar%2!=0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)

arr=np.arange(1,8)

print(arr+2)
print(arr*2)
print(arr**2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


In [93]:
arr=np.array([10,20,30,25,6,2])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.sin(arr))
print(np.cos(arr))

2
30
5
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [101]:
np.random.seed(122)
mat=np.random.randint(1,21,9).reshape(3,3)
print(mat)
print(np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print(np.sum(mat,axis=1))
print(np.min(mat,axis=1))
print(np.max(mat,axis=1))
print(np.cumsum(mat,axis=1))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [105]:
np.random.seed(122)
mat=np.random.randint(1,21,10)
print(mat)
np.random.shuffle(mat)
print(mat)
print(np.unique(mat,return_index=True,return_counts=True))
print(np.unique(mat).size)


[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
6
