In [1]:
# mean 
import numpy as np 


In [7]:
# np.slpit()
arr=np.array([1,2,3,4,5,6]) 
sub_arrays=np.split(arr,3) 
for sub_arr in sub_arrays:
    print(sub_arr)

[1 2]
[3 4]
[5 6]


In [ ]:
'''In NumPy, you can use the np.sort() function to sort elements in an array along a specified axis. 
This function returns a sorted copy of the original array. 
Additionally, you can use the array.sort() method to sort an array in-place, modifying the original array. Here's how to use both approaches:'''

In [17]:
#np.sort()
arr = np.array([3, 1, 2, 4, 5]) 
sorted_arr = np.sort(arr)
print("Sorted array (ascending):", sorted_arr)
sorted_arr_desc = np.sort(arr)[::-1]
#Printthesortedarrayindescendingorder 
print("Sortedarray(descending):",sorted_arr_desc)

Sorted array (ascending): [1 2 3 4 5]
Sortedarray(descending): [5 4 3 2 1]


In [21]:
#Sorting Along Specific Axis (For Multi-dimensional Arrays
matrix=np.array([[3,1,2], [6,5,4]]) 
#Sort along rows (axis=1)in ascending order 
sorted_matrix=np.sort(matrix,axis=1)
#Printthesortedmatrix 
print("Sorted matrix (ascending along rows):") 
print(sorted_matrix)

Sorted matrix (ascending along rows):
[[1 2 3]
 [4 5 6]]


In [23]:
# np.concatenate():
'''The np.concatenate() function is used to join arrays along a specifiedaxis. 
Ittakesasequenceofarraysasinputandconcatenatesthemalongthe specifiedaxis.'''


'The np.concatenate() function is used to join arrays along a specifiedaxis. \nIttakesasequenceofarraysasinputandconcatenatesthemalongthe specifiedaxis.'

In [25]:
arr1=np.array([[1,2], [3,4]]) 
arr2=np.array([[5,6]]) 

result=np.concatenate((arr1,arr2),axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]]


In [33]:
arr1=np.array([[1,2], [3,4]]) 
arr2=np.array([[5],[6]]) 

result=np.concatenate((arr1,arr2),axis=1)

print(result)

[[1 2 5]
 [3 4 6]]


In [37]:
# .np.vstack()andnp.hstack(): 
# np.vstack():Stacksarraysvertically(alongrows).
arr1=np.array([1,2,3])
arr2=np.array([4,5,6]) 

result=np.vstack((arr1,arr2))


print(result)

[[1 2 3]
 [4 5 6]]


In [39]:
# np.hstack():Stacksarrayshorizontally(alongcolumns).
arr1=np.array([1,2])
arr2=np.array([3,4]) 

result=np.hstack((arr1,arr2))

print(result)

[1 2 3 4]


In [41]:
# NumpyFilter 
# InNumPy, youcanfilter elements inanarraybasedonaspecifiedconditionusing booleanindexing.
# Booleanindexingallowsyoutocreateamask(abooleanarray)that selectselementsfromtheoriginalarraythatmeetthespecifiedcondition
# .Here'showto filterelementsinaNumPyarray:

In [45]:
#CreateaNumPyarray 
arr=np.array([1,2,3,4,5,6])
#Create a boolean mask based on a condition (e.g.,values greater than 3) 
mask=(arr>3) 
#Use the mask to filter elements in the array
filtered_array=arr[mask]
#Print the filtered array 
print("FilteredArray:",filtered_array)

FilteredArray: [4 5 6]


In [47]:
#. Filter: 
# Real-Life Scenario: Filtering Sensor Data
temperatures = np.array([20.5, 22.0, 19.8, 23.5, 18.0, 24.2, 26.1])

filtered_temperatures = temperatures[(temperatures >= 20) & (temperatures <= 25)] 
print("Filtered Temperatures:") 
print(filtered_temperatures)

Filtered Temperatures:
[20.5 22.  23.5 24.2]


In [49]:
#mean #var #std
#mean
classA= np.array([85, 88, 90, 92, 95])
classA_mean=np.mean(classA)
print('Class A Score Average',classA_mean )
classA_std=np.std(classA)
print('Class A Standard Deviation',classA_std )#std
classA_var=np.var(classA)
print('Class A Variance',classA_var)#var

Class A Score Average 90.0
Class A Standard Deviation 3.40587727318528
Class A Variance 11.6


In [59]:
# Test scores of 30 students
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
                        110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138])
median = np.percentile(test_scores, 25)
print("Median (50th Percentile):", median)

Median (50th Percentile): 95.25


In [ ]:
# np.load() is a function in the NumPy library used to load data from a binary file. 
# It is typically used to load previously saved NumPy arrays or objects that were saved using np.save() or a similar function.

In [61]:
# Sample student scores
scores = np.array([85, 92, 78, 88, 95, 72, 89])
# Save the scores to a file
np.save('student_scores.npy', scores)
# Load the scores from the file
loaded_scores = np.load('student_scores.npy')
print("Original Scores:", scores)
print("Loaded Scores:", loaded_scores)

Original Scores: [85 92 78 88 95 72 89]
Loaded Scores: [85 92 78 88 95 72 89]
