In [3]:
# numpy assignment 
# ques 1 
# convert the below list into numpy array then display the array 
#input :- my_list=[1,2,3,4,5]

import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)


[1 2 3 4 5]


In [5]:
 #ques 2 
# convert the below list into a numpy array then display the array then display the first and last index and then multiply each 
#element by 2 and dispaly the result 
# input list :- my_list =[1,2,3,4,5]

import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("Array:", my_array)
print("First element:", my_array[0])
print("Last element:", my_array[-1])
multiplied_array = my_array * 2

print("Array after multiplying by 2:", multiplied_array)


Array: [1 2 3 4 5]
First element: 1
Last element: 5
Array after multiplying by 2: [ 2  4  6  8 10]


In [27]:
#ques 3 
# write a numpy program to create an array of 10 zeros, 10 ones , and 10 fives 


import numpy as np
zeros_array = np.zeros(10, dtype=int)
ones_array = np.ones(10, dtype=int)
fives_array = np.full(10, 5, dtype=int)
print("an array of 10 zeroes:")
print(zeros_array)
print("an array of 10 ones :")
print(ones_array)
print("an array of 10 fives :")
print(fives_array)

an array of 10 zeroes:
[0 0 0 0 0 0 0 0 0 0]
an array of 10 ones :
[1 1 1 1 1 1 1 1 1 1]
an array of 10 fives :
[5 5 5 5 5 5 5 5 5 5]


In [29]:
#ques 4 
# write a numPy program to create a 3x3 matrix with valuees ranging from 2 to 10 

import numpy as np
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:")
print(matrix)


3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
